# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: add51572de270e2d526d2129f4fbee2dfe6bb493a2745ab5535d6e7f991d0833c043c70ab68589c318038f230a654458a19a1ded4e552ac1f85cf4e63c870667

test:
  secret_key_base: faad380eddd3d81adfa4e9d12091e5f455fd50991968b84a3e4e5552003f0495bfc6896887a04401aeda1f4446121c5c4512e249329c16c7780be4066a410c29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
